import yaml

with open('config.yaml', 'r') as f:
    data = yaml.full_load(f)

BATCH_SIZES = data["TRAINING_PARAMS"]["BATCH_SIZES"]
LR_GEN = data["TRAINING_PARAMS"]["LR_GEN"]
LR_DISC = data["TRAINING_PARAMS"]["LR_DISC"]
CHECKPOINT_FOLDER = data["TRAINING_PARAMS"]["CHECKPOINT_FOLDER"]
IM_PATH = data["TRAINING_PARAMS"]["IM_PATH"]
MAX_SIZE_I = data["TRAINING_PARAMS"]["MAX_SIZE_I"]
CROP_SIZE = data["TRAINING_PARAMS"]["CROP_SIZE"]
SAVE_AFTER = data["TRAINING_PARAMS"]["SAVE_AFTER"]
EPOCH_DICT = data["TRAINING_PARAMS"]["EPOCH_DICT"]