TRAINING_PARAMS:
  LR_GEN: !!float 1e-3
  LR_DISC: !!float 1e-3
  CHECKPOINT_FOLDER: "checkpoint"
  BATCH_SIZES: {4: 64, 8: 32, 16: 32, 32: 16, 64: 8, 128: 8, 256: 8, 512: 8}
  IM_PATH: "data/images/"
  MAX_SIZE_I: 6
  CROP_SIZE: 160
  SAVE_AFTER: 1
  EPOCH_DICT: {4: 128, 8: 128, 16: 128, 32: 128, 64: 64, 128: 64, 256: 64, 512: 32}


