import torchvision.transforms as transforms
import matplotlib.pyplot as plt
# Visualization the dataset

def visualize_imgs_test(a, b, gen_a=None, gen_b=None, figsize=(8,5)):
    # imgA, imgB: torch tensor
    # genA, genB: should be fake images generated by the two generators, should pass them at the same time or not
    # resize: None as default and tuple if stated.
    # imgA, imgB: low resolution; genA, genB: sr; hrA, hrB.

    #imgA = (imgA + 1) / 2
    #imgB = (imgB + 1) / 2
    a = (a + 1) / 2
    b = (b + 1) / 2



    a = transforms.ToPILImage()(a)
    b = transforms.ToPILImage()(b)
    if gen_a is not None and gen_b is not None:
        gen_a = (gen_a + 1) / 2
        gen_b = (gen_b + 1) / 2
        gen_a = transforms.ToPILImage()(gen_a)
        gen_b = transforms.ToPILImage()(gen_b)

        fig, axes = plt.subplots(2, 2, figsize=figsize)

        # Display images
        axes[0, 0].imshow(a)
        axes[0, 0].axis("off")

        axes[0, 1].imshow(gen_a)
        axes[0, 1].axis("off")

        axes[1, 0].imshow(b)
        axes[1, 0].axis("off")

        axes[1, 1].imshow(gen_b)
        axes[1, 1].axis("off")
    else:
        fig, axes = plt.subplots(1, 2, figsize=figsize)

        # Display images
        axes[0].imshow(a)
        #axes[0].axis("off")

        axes[1].imshow(b)
        #axes[1].axis("off")

    plt.tight_layout()
    plt.show()
import matplotlib.pyplot as plt
from torchvision import transforms
import random
from pathlib import Path
import torch
from datetime import datetime, timedelta, timezone # To save the model

import sys

# Visualization the dataset

def visualize_imgs(imgA, imgB, genA=None, genB=None, resize=None, figsize=(15,20)):
    # imgA, imgB: torch tensor
    # genA, genB: should be fake images generated by the two generators, should pass them at the same time or not
    # resize: None as default and tuple if stated.

    imgA = (imgA + 1) / 2
    imgB = (imgB + 1) / 2

    imgA = transforms.ToPILImage()(imgA)
    imgB = transforms.ToPILImage()(imgB)
    # Resize the images
    if resize is not None:
        resize_img = transforms.Resize(resize)
        imgA = resize_img(imgA)
        imgB = resize_img(imgB)
    if genA is None or genB is None:
        fix, axes = plt.subplots(1, 2, figsize=figsize)
        axes[0].imshow(imgA)
        axes[0].axis("off")
        axes[1].imshow(imgB)
        axes[1].axis("off")
        plt.tight_layout()
        plt.show()
    else:

        genA = (genA + 1) / 2
        genB = (genB + 1) / 2

        genA = transforms.ToPILImage()(genA)
        genB = transforms.ToPILImage()(genB)
        if resize is not None:
            resize_img = transforms.Resize(resize)
            genA = resize_img(genA)
            genB = resize_img(genB)
        fix, axes = plt.subplots(1, 4, figsize=figsize)
        axes[0].imshow(imgA)
        axes[0].axis("off")
        axes[1].imshow(imgB)
        axes[1].axis("off")
        axes[2].imshow(genA)
        axes[2].axis("off")
        axes[3].imshow(genB)
        axes[3].axis("off")
        plt.tight_layout()
        plt.show()
def select_img(pool_imgs, imA, imB, max_len=50):
    """
    CycleGAN image buffer: returns either the current images
    or previously stored ones. Ensures tensors are detached.
    """
    imA = imA.detach().clone()
    imB = imB.detach().clone()

    if len(pool_imgs) < max_len:
        pool_imgs.append((imA, imB))
        return imA, imB
    elif random.random() < 0.5:
        return imA, imB
    else:
        idx = random.randrange(len(pool_imgs))
        oldA, oldB = pool_imgs[idx]
        pool_imgs[idx] = (imA, imB)
        return oldA, oldB

def save_model(model, save_path, model_name, epoch=None, optimizer=None, loss=None, log=None):
    # Define GMT+7 timezone
    gmt7 = timezone(timedelta(hours=7))
    now_gmt7 = datetime.now(gmt7)
    y = now_gmt7.year
    m = now_gmt7.month
    d = now_gmt7.day
    h = now_gmt7.hour
    mi = now_gmt7.minute
    s = now_gmt7.second

    checkpoint = {
            'model_state_dict': model.state_dict(),
        }
    extra = {}
    if epoch:
        checkpoint["epoch"] = epoch
        extra["epoch"] = epoch
    if loss:
        checkpoint["loss"] = loss
        extra["loss"] = loss
    if optimizer:
        checkpoint["optimizer"] = optimizer.state_dict()
        extra["optimizer"] = "save with optimizer"
    save_path = Path(save_path) / f'{model_name}_{y}_{m}_{d}_{h}_{mi}_{s}_at_epoch_{epoch}.pth'
    extra["save_path"] = str(save_path)
    torch.save(checkpoint, save_path)
    if log: #use info level
        log.info(f'save_model', extra=extra)
    return f"Save model at {save_path}"
def create_folder(create_folder):
    folder = Path.cwd() / create_folder
    folder.mkdir(parents=True, exist_ok=True)
    return folder




def get_environment():
    """
    Detects the runtime environment.

    Returns:
        str: 'Colab', 'Jupyter', or 'Script'
    """

    # Check for Google Colab
    if 'google.colab' in sys.modules:
        return 'Colab'

    # Check for general Jupyter environment
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            return 'Jupyter'  # Jupyter notebook, JupyterLab, QtConsole
        elif shell == 'TerminalInteractiveShell':
            return 'Script'  # Standard IPython terminal
        else:
            return 'Script'  # Other (e.g., IDLE)
    except NameError:
        return 'Script'  # Not in an IPython environment

def get_tqdm():
    env = get_environment()
    if env == 'Jupyter' or env == 'Colab':
        from tqdm.notebook import tqdm
    else:
        from tqdm import tqdm
    return tqdm

def get_argparge_type(parser):
    env = get_environment()
    if env == 'Jupyter' or env == 'Colab':
        config_args, _ = parser.parse_known_args()
    else:
        config_args = parser.parse_args() # This is for the scripts py
    return config_args
def get_alpha(epoch_val, batch_val, total_epoch, total_batch):
    """
    Return the current alpha.
    epoch_val: start with 0 => first epoch we will have the current_batch = batch_val + 0
    batch_val: the current batch value in total batch
    total_epoch: total epochs for that resolution training.
    total_batch: number of batch for that epoch.
    first_half: alpha goes from 0 -> 1
    the other half: alpha=1
    """
    first_half = total_epoch // 2

    if epoch_val < first_half:
        current_batch = batch_val + epoch_val * total_batch
        total_batch_half = total_batch * first_half
        return current_batch / total_batch_half
    else:
        return 1
