import matplotlib.pyplot as plt
from torchvision import transforms
import random
# Visualization the dataset

def visualize_imgs(imgA, imgB, genA=None, genB=None, resize=None, figsize=(15,20)):
    # imgA, imgB: torch tensor
    # genA, genB: should be fake images generated by the two generators, should pass them at the same time or not
    # resize: None as default and tuple if stated.

    imgA = (imgA + 1) / 2
    imgB = (imgB + 1) / 2

    imgA = transforms.ToPILImage()(imgA)
    imgB = transforms.ToPILImage()(imgB)
    # Resize the images
    if resize is not None:
        resize_img = transforms.Resize(resize)
        imgA = resize_img(imgA)
        imgB = resize_img(imgB)
    if genA is None or genB is None:
        fix, axes = plt.subplots(1, 2, figsize=figsize)
        axes[0].imshow(imgA)
        axes[0].axis("off")
        axes[1].imshow(imgB)
        axes[1].axis("off")
        plt.tight_layout()
        plt.show()
    else:

        genA = (genA + 1) / 2
        genB = (genB + 1) / 2

        genA = transforms.ToPILImage()(genA)
        genB = transforms.ToPILImage()(genB)
        if resize is not None:
            resize_img = transforms.Resize(resize)
            genA = resize_img(genA)
            genB = resize_img(genB)
        fix, axes = plt.subplots(1, 4, figsize=figsize)
        axes[0].imshow(imgA)
        axes[0].axis("off")
        axes[1].imshow(imgB)
        axes[1].axis("off")
        axes[2].imshow(genA)
        axes[2].axis("off")
        axes[3].imshow(genB)
        axes[3].axis("off")
        plt.tight_layout()
        plt.show()
def select_img(pool_imgs, imA, imB, max_len=50):
    """
    CycleGAN image buffer: returns either the current images
    or previously stored ones. Ensures tensors are detached.
    """
    imA = imA.detach().clone()
    imB = imB.detach().clone()

    if len(pool_imgs) < max_len:
        pool_imgs.append((imA, imB))
        return imA, imB
    elif random.random() < 0.5:
        return imA, imB
    else:
        idx = random.randrange(len(pool_imgs))
        oldA, oldB = pool_imgs[idx]
        pool_imgs[idx] = (imA, imB)
        return oldA, oldB
if __name__ == "__main__":
    from dataset import Custom_dataset
    test_dataset = Custom_dataset("./data/trainA", "./data/trainB", use_transformA=True, use_transformB=True)
    visualize_imgs(test_dataset[200][0], test_dataset[200][1],test_dataset[200][0], test_dataset[200][1], resize=(256, 256))